In [29]:
#Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
#importing the dataset
dataset = pd.read_csv('car data.csv')
X = dataset.drop(['Selling_Price','Car_Name'],axis=1).values
y = dataset['Selling_Price'].values

In [11]:
X

array([[2014, 5.59, 27000, ..., 'Dealer', 'Manual', 0],
       [2013, 9.54, 43000, ..., 'Dealer', 'Manual', 0],
       [2017, 9.85, 6900, ..., 'Dealer', 'Manual', 0],
       ...,
       [2009, 11.0, 87934, ..., 'Dealer', 'Manual', 0],
       [2017, 12.5, 9000, ..., 'Dealer', 'Manual', 0],
       [2016, 5.9, 5464, ..., 'Dealer', 'Manual', 0]], dtype=object)

In [12]:
#Encoding the Independent Variables
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3,4,5])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [24]:
#Checking the encoding
print(X[1])

[0.0 1.0 0.0 1.0 0.0 0.0 1.0 2013 9.54 43000 0]


In [ ]:
# For Fuel_Type
# -> Petrol = [0,0,1]
# -> Diesel = [0,1,0]
# -> LPG = [1,0,0]

# For Seller_Type
# -> Dealer = [1,0]
# -> Individual = [0,1]

# For Transmission
# -> Manual = [0,1]
# -> Automatic = [1,0]

In [13]:
X

array([[0.0, 0.0, 1.0, ..., 5.59, 27000, 0],
       [0.0, 1.0, 0.0, ..., 9.54, 43000, 0],
       [0.0, 0.0, 1.0, ..., 9.85, 6900, 0],
       ...,
       [0.0, 0.0, 1.0, ..., 11.0, 87934, 0],
       [0.0, 1.0, 0.0, ..., 12.5, 9000, 0],
       [0.0, 0.0, 1.0, ..., 5.9, 5464, 0]], dtype=object)

In [16]:
# Applying Random Forest Regression Model
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
prediction=regressor.fit(X, y)

In [28]:
#Calculating the r2 score
from sklearn.metrics import r2_score
print(r2_score(y,regressor.predict(X)))

0.9742407626332721


In [26]:
#Predicting for:
# Year= 2015, Present_Price=8.12, Kms_Driven=19000, Owner=0, Fuel_Type=Petrol, Seller_Type= Dealer, Transmission= Manual

regressor.predict([[0.0,0.0,1.0,1.0,0.0,0.0,1.0,2015,8.12,19000,0]])

array([6.435])